"""ADD Modelos de Purchases.

Revision ID: 05e09eb4c6f0
Revises: 54e923519e95
Create Date: 2026-01-29 17:54:09.918012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05e09eb4c6f0'
down_revision: Union[str, Sequence[str], None] = '54e923519e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
                    sa.Column(
                        'Selling_rep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('PickUp_person',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Delivery_location',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Return_request',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Return_status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Purchase_note',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Total_spending', sa.Float(), nullable=True),
                    sa.Column('ID_Purchase', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Member', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Member'], ['member.ID_Member'], ),
                    sa.PrimaryKeyConstraint('ID_Purchase')
                    )
    op.create_index(op.f('ix_purchase_podio_item_id'),
                    'purchase', ['podio_item_id'], unique=False)
    op.create_table('purchase_order',
                    sa.Column(
                        'Order_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Est_delivery_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('Order_confirmation',
                              sa.Boolean(), nullable=True),
                    sa.Column('ID_PurchaseOrder',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Purchase', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Purchase'], ['purchase.ID_Purchase'], ),
                    sa.PrimaryKeyConstraint('ID_PurchaseOrder')
                    )
    op.create_index(op.f('ix_purchase_order_podio_item_id'),
                    'purchase_order', ['podio_item_id'], unique=False)
    op.create_table('purchase_supplier',
                    sa.Column(
                        'purchase_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['purchase_id'], ['purchase.ID_Purchase'], ),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['supplier.ID_Supplier'], ),
                    sa.PrimaryKeyConstraint('purchase_id', 'supplier_id')
                    )
    op.create_table('purchase_order_item',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Quote_shop', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Quote_link', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('Quote_value', sa.Float(), nullable=True),
                    sa.Column('Purchase_shop',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Purchase_link',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Purchase_value', sa.Float(), nullable=True),
                    sa.Column('ID_PurchaseOrderItem',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_PurchaseOrder',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_PurchaseOrder'], [
                        'purchase_order.ID_PurchaseOrder'], ),
                    sa.PrimaryKeyConstraint('ID_PurchaseOrderItem')
                    )
    op.create_index(op.f('ix_purchase_order_item_podio_item_id'),
                    'purchase_order_item', ['podio_item_id'], unique=False)
    op.add_column('supplier', sa.Column('podio_item_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('supplier', 'Company_Name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Company_Website',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Acc_Status',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Acc_Rep',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Email_Address',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Coverage_Area',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('supplier', 'Phone_Number',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.create_index(op.f('ix_supplier_podio_item_id'),
                    'supplier', ['podio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_podio_item_id'), table_name='supplier')
    op.alter_column('supplier', 'Phone_Number',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Coverage_Area',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Email_Address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Acc_Rep',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Acc_Status',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Company_Website',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('supplier', 'Company_Name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('supplier', 'podio_item_id')
    op.drop_index(op.f('ix_purchase_order_item_podio_item_id'),
                  table_name='purchase_order_item')
    op.drop_table('purchase_order_item')
    op.drop_table('purchase_supplier')
    op.drop_index(op.f('ix_purchase_order_podio_item_id'),
                  table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_purchase_podio_item_id'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
