"""ADD StandardPS y relación con Client.

Revision ID: 09d414398455
Revises: d0eee064fa99
Create Date: 2026-02-02 12:13:27.047817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09d414398455'
down_revision: Union[str, Sequence[str], None] = 'd0eee064fa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_ps',
                    sa.Column(
                        'Item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Quantity', sa.Float(), nullable=True),
                    sa.Column('Unit_price', sa.Float(), nullable=True),
                    sa.Column('Price', sa.Float(), nullable=True),
                    sa.Column(
                        'Category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_StandardPS',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Client'], ['client.ID_Client'], ),
                    sa.PrimaryKeyConstraint('ID_StandardPS')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standard_ps')
    # ### end Alembic commands ###
