"""MODIFY Modelo Change Order para relación con Podio.

Revision ID: 0e518cb3f9db
Revises: 7a201fb92740
Create Date: 2026-02-13 11:35:08.449355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e518cb3f9db'
down_revision: Union[str, Sequence[str], None] = '7a201fb92740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_order', sa.Column('job_podio_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('change_order', sa.Column(
        'podio_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_order', 'podio_field')
    op.drop_column('change_order', 'job_podio_id')
    # ### end Alembic commands ###
