"""add chat_message model

Revision ID: 0f30cb1e8da7
Revises: 9d1d91bc81c5
Create Date: 2026-03-18 12:17:42.112812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f30cb1e8da7'
down_revision: Union[str, Sequence[str], None] = '9d1d91bc81c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
                    sa.Column(
                        'content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_ChatMessage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column(
                        'ID_Job', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ID_Member', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['ID_Job'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Member'], ['member.ID_Member'], ),
                    sa.PrimaryKeyConstraint('ID_ChatMessage')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ###
