"""ADD Modelo de QBO Tokens.

Revision ID: 11e2c22efef4
Revises: 2a317a04c9c1
Create Date: 2026-01-26 18:27:45.071711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11e2c22efef4'
down_revision: Union[str, Sequence[str], None] = '2a317a04c9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quickbookstoken',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'realm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('refresh_token',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('expires_in', sa.Integer(), nullable=False),
                    sa.Column('refresh_token_expires_in',
                              sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_quickbookstoken_realm_id'),
                    'quickbookstoken', ['realm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quickbookstoken_realm_id'),
                  table_name='quickbookstoken')
    op.drop_table('quickbookstoken')
    # ### end Alembic commands ###
