"""add access_level to attachments

Revision ID: 17ec7a035217
Revises: 6bf35f1f3c67
Create Date: 2026-04-13 18:38:52.295149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17ec7a035217'
down_revision: Union[str, Sequence[str], None] = '6bf35f1f3c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_attachments_access_level'), 'attachments', ['access_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_access_level'), table_name='attachments')
    op.drop_column('attachments', 'access_level')
    # ### end Alembic commands ###
