"""[MODIFY] Relacion entre Subc+Tasks y Order+FinancialDoc

Revision ID: 1c3b6eca42b5
Revises: 68d377c61548
Create Date: 2026-04-15 23:23:01.425348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c3b6eca42b5'
down_revision: Union[str, Sequence[str], None] = '68d377c61548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_document', sa.Column('ID_Order', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'financial_document', 'order', ['ID_Order'], ['ID_Order'])
    op.add_column('tasks', sa.Column('ID_Subcontractor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'subcontractor', ['ID_Subcontractor'], ['ID_Subcontractor'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'ID_Subcontractor')
    op.drop_constraint(None, 'financial_document', type_='foreignkey')
    op.drop_column('financial_document', 'ID_Order')
    # ### end Alembic commands ###
