"""Add Is_extra column to Purchase

Revision ID: 28b4126e75fc
Revises: cbdd681a9cbb
Create Date: 2026-05-08 07:10:36.266034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b4126e75fc'
down_revision: Union[str, Sequence[str], None] = 'cbdd681a9cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('Is_extra', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'Is_extra')
    # ### end Alembic commands ###
