"""initial schema

Revision ID: 2ae2b1740857
Revises: 
Create Date: 2026-01-20 15:55:48.900571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2ae2b1740857'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transaction',
                    sa.Column('Type_of_transaction', sa.Enum(
                        'Bill_payments', 'Invoice_payments', name='transactiontype'), nullable=False),
                    sa.Column('Reference_number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Total_Amount', sa.Float(), nullable=True),
                    sa.Column('Bank_Account_Ref',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Type_of_payment',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Date_of_payment', sa.Date(), nullable=True),
                    sa.Column('ID_FTransaction',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'qbo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('ID_FTransaction')
                    )
    op.create_table('multiplier_range',
                    sa.Column('Start_value', sa.Float(), nullable=True),
                    sa.Column('End_value', sa.Float(), nullable=True),
                    sa.Column('Multiplier', sa.Float(), nullable=True),
                    sa.Column('ID_MultiplierR',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('ID_MultiplierR')
                    )
    op.create_table('parent_mgmt_co',
                    sa.Column('Property_mgmt_co',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Company_abbrev',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Main_office_hq',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Main_office_email',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Main_office_number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'State', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Community_Tracking',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('ID_Community_Tracking')
                    )
    op.create_table('payment_unit',
                    sa.Column('Total_amount_paid', sa.Float(), nullable=True),
                    sa.Column('Description_payment',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Percentage_paid', sa.Float(), nullable=True),
                    sa.Column('Percentage_remaining_to_pay',
                              sa.Float(), nullable=True),
                    sa.Column('Type_of_payment',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Date', sa.DateTime(), nullable=True),
                    sa.Column('ID_PaymentU', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('ID_PaymentU')
                    )
    op.create_table('permission',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Active', sa.Boolean(), nullable=True),
                    sa.Column('Action', sa.Enum('View', 'Create', 'Edit',
                                                'Delete', name='actiontype'), nullable=False),
                    sa.Column('Service_Associated', sa.Enum('Job', 'Subcontractor', 'GQM_Member',
                                                            'Technician', 'Client', 'Dashboard', name='servicetype'), nullable=False),
                    sa.Column('ID_Permission',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('ID_Permission')
                    )
    op.create_table('role',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Active', sa.Boolean(), nullable=True),
                    sa.Column(
                        'ID_Role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('ID_Role')
                    )
    op.create_table('skills',
                    sa.Column(
                        'Skill_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Division_trade',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Skill', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('ID_Skill')
                    )
    op.create_table('supplier',
                    sa.Column(
                        'Company_Name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'Company_Website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('Acc_Status', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'Acc_Rep', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Speciality', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('Email_Address',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Coverage_Area',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Phone_Number', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'Address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Supplier', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('ID_Supplier')
                    )
    op.create_table('client',
                    sa.Column('Client_Community',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Parent_Mgmt_Company',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Invoice_Collection',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Compliance_Partner',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Risk_Value', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('Maintenance_Sup',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Email_Address',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Phone_Number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Client_Status',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Services_interested_in',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Collection_Process',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Payment_Collection',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Client', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Community_Tracking',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Community_Tracking'], [
                        'parent_mgmt_co.ID_Community_Tracking'], ),
                    sa.PrimaryKeyConstraint('ID_Client')
                    )
    op.create_index(op.f('ix_client_podio_item_id'),
                    'client', ['podio_item_id'], unique=False)
    op.create_table('manager',
                    sa.Column(
                        'Manager_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Manager_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Manager_location',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Rol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Manager', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_Community_Tracking',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Community_Tracking'], [
                        'parent_mgmt_co.ID_Community_Tracking'], ),
                    sa.PrimaryKeyConstraint('ID_Manager')
                    )
    op.create_table('member',
                    sa.Column(
                        'Member_Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Email_Address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Phone_Number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Password', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_Member', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'ID_Role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Role'], ['role.ID_Role'], ),
                    sa.PrimaryKeyConstraint('ID_Member')
                    )
    op.create_table('permission_role',
                    sa.Column(
                        'permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'role_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['permission_id'], ['permission.ID_Permission'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.ID_Role'], ),
                    sa.PrimaryKeyConstraint('permission_id', 'role_id')
                    )
    op.create_table('subcontractor',
                    sa.Column(
                        'Organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Email_Address',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Phone_Number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Organization_Website',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Score', sa.Float(), nullable=True),
                    sa.Column('Gqm_compliance',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Gqm_best_service_training',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Specialty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Coverage_Area', postgresql.JSON(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column(
                        'Notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Role'], ['role.ID_Role'], ),
                    sa.PrimaryKeyConstraint('ID_Subcontractor')
                    )
    op.create_table('client_manager',
                    sa.Column(
                        'clients_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'manager_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['clients_id'], ['client.ID_Client'], ),
                    sa.ForeignKeyConstraint(
                        ['manager_id'], ['manager.ID_Manager'], ),
                    sa.PrimaryKeyConstraint('clients_id', 'manager_id')
                    )
    op.create_table('client_member',
                    sa.Column(
                        'clients_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'members_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'rol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['clients_id'], ['client.ID_Client'], ),
                    sa.ForeignKeyConstraint(
                        ['members_id'], ['member.ID_Member'], ),
                    sa.PrimaryKeyConstraint('clients_id', 'members_id')
                    )
    op.create_table('jobs',
                    sa.Column('Job_type', sa.Enum('QID', 'PTL',
                              'PAR', name='jobtype'), nullable=False),
                    sa.Column(
                        'Project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Project_location',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Job_status', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'Po_wtn_wo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Service_type',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Date_assigned', sa.DateTime(), nullable=True),
                    sa.Column('Estimated_start_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('Estimated_project_duration',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Date_Received', sa.DateTime(), nullable=True),
                    sa.Column('Estimated_completion_date',
                              sa.DateTime(), nullable=True),
                    sa.Column('Gqm_formula_pricing',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_adj_formula_pricing',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_target_sold_pricing',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_target_return', sa.Float(), nullable=True),
                    sa.Column('Gqm_premium_in_money',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_final_sold_pricing',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_final_percentage',
                              sa.Float(), nullable=True),
                    sa.Column('Gqm_total_change_orders',
                              sa.Float(), nullable=True),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['ID_Client'], ['client.ID_Client'], ),
                    sa.PrimaryKeyConstraint('ID_Jobs')
                    )
    op.create_index(op.f('ix_jobs_podio_item_id'), 'jobs',
                    ['podio_item_id'], unique=False)
    op.create_table('order',
                    sa.Column(
                        'Title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Formula', sa.Float(), nullable=True),
                    sa.Column('Adj_formula', sa.Float(), nullable=True),
                    sa.Column('job_podio_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('tech_field', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('ID_Order', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('ID_Order')
                    )
    op.create_table('permission_member',
                    sa.Column(
                        'permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['member_id'], ['member.ID_Member'], ),
                    sa.ForeignKeyConstraint(
                        ['permission_id'], ['permission.ID_Permission'], ),
                    sa.PrimaryKeyConstraint('permission_id', 'member_id')
                    )
    op.create_table('skills_subcontractors',
                    sa.Column(
                        'subcon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'skills_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Certificated', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['skills_id'], ['skills.ID_Skill'], ),
                    sa.ForeignKeyConstraint(
                        ['subcon_id'], ['subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('subcon_id', 'skills_id')
                    )
    op.create_table('technician',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Email_Address',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('Phone_Number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Type_of_technician',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Password', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_Technician',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('ID_Technician')
                    )
    op.create_table('attachments',
                    sa.Column(
                        'Document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Attachment_descr',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Document_type',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Attachment',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Technician',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Technician'], ['technician.ID_Technician'], ),
                    sa.PrimaryKeyConstraint('ID_Attachment')
                    )
    op.create_table('change_order',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ChangeOrderFormula', sa.Float(), nullable=True),
                    sa.Column(
                        'State', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_ChangeOrder',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.PrimaryKeyConstraint('ID_ChangeOrder')
                    )
    op.create_table('estimate_cost',
                    sa.Column(
                        'Title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Cost_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Parent_group',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('Quatity', sa.Float(), nullable=True),
                    sa.Column(
                        'Unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Unit_cost', sa.Float(), nullable=True),
                    sa.Column(
                        'Cost_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Builder_cost', sa.Float(), nullable=True),
                    sa.Column('Client_price', sa.Float(), nullable=True),
                    sa.Column('Markup', sa.Float(), nullable=True),
                    sa.Column('Margin', sa.Float(), nullable=True),
                    sa.Column('Percent_invoiced', sa.Float(), nullable=True),
                    sa.Column(
                        'Status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_EstimateCost',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Order'], ['order.ID_Order'], ),
                    sa.PrimaryKeyConstraint('ID_EstimateCost')
                    )
    op.create_table('financial_document',
                    sa.Column('Type_of_document', sa.Enum(
                        'Bill', 'Invoice', name='documenttype'), nullable=False),
                    sa.Column(
                        'Job_Ref_QBO', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Total_Amount', sa.Float(), nullable=True),
                    sa.Column('Balance_Amount', sa.Float(), nullable=True),
                    sa.Column('Percentage_Paid', sa.Float(), nullable=True),
                    sa.Column(
                        'Notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Due_Date', sa.Date(), nullable=True),
                    sa.Column('ID_FinancialDoc',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'qbo_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Client'], ['client.ID_Client'], ),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Order'], ['order.ID_Order'], ),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('ID_FinancialDoc')
                    )
    op.create_table('job_member',
                    sa.Column(
                        'job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['member_id'], ['member.ID_Member'], ),
                    sa.PrimaryKeyConstraint('job_id', 'member_id')
                    )
    op.create_table('job_multiplier_range',
                    sa.Column(
                        'job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'multiplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['multiplier_id'], ['multiplier_range.ID_MultiplierR'], ),
                    sa.PrimaryKeyConstraint('job_id', 'multiplier_id')
                    )
    op.create_table('job_payment_unit',
                    sa.Column(
                        'job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'payment_unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(['payment_unit_id'], [
                        'payment_unit.ID_PaymentU'], ),
                    sa.PrimaryKeyConstraint('job_id', 'payment_unit_id')
                    )
    op.create_table('job_subcontractor',
                    sa.Column(
                        'job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'subcontr_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['subcontr_id'], ['subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('job_id', 'subcontr_id')
                    )
    op.create_table('opportunities',
                    sa.Column(
                        'Project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('State', sa.Boolean(), nullable=True),
                    sa.Column(
                        'Priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Start_Date', sa.DateTime(), nullable=True),
                    sa.Column('ID_Opportunities',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.PrimaryKeyConstraint('ID_Opportunities')
                    )
    op.create_table('permission_tech',
                    sa.Column(
                        'permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'tech_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['permission_id'], ['permission.ID_Permission'], ),
                    sa.ForeignKeyConstraint(
                        ['tech_id'], ['technician.ID_Technician'], ),
                    sa.PrimaryKeyConstraint('permission_id', 'tech_id')
                    )
    op.create_table('tasks',
                    sa.Column('Task_description',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Task_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Designation_date', sa.Date(), nullable=True),
                    sa.Column('Delivery_date', sa.Date(), nullable=True),
                    sa.Column(
                        'Priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Tasks', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Technician',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Technician'], ['technician.ID_Technician'], ),
                    sa.PrimaryKeyConstraint('ID_Tasks')
                    )
    op.create_index(op.f('ix_tasks_podio_item_id'), 'tasks',
                    ['podio_item_id'], unique=False)
    op.create_table('tlactivity',
                    sa.Column(
                        'Action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Action_datetime', sa.DateTime(), nullable=True),
                    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('ID_TLActivity',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'ID_Member', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Technician',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Member'], ['member.ID_Member'], ),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.ForeignKeyConstraint(
                        ['ID_Technician'], ['technician.ID_Technician'], ),
                    sa.PrimaryKeyConstraint('ID_TLActivity')
                    )
    op.create_table('fdocument_ftransaction',
                    sa.Column(
                        'fdocument_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ftransaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['fdocument_id'], ['financial_document.ID_FinancialDoc'], ),
                    sa.ForeignKeyConstraint(['ftransaction_id'], [
                        'financial_transaction.ID_FTransaction'], ),
                    sa.PrimaryKeyConstraint('fdocument_id', 'ftransaction_id')
                    )
    op.create_table('financial_doc_item',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Unit_price', sa.Float(), nullable=True),
                    sa.Column('Quantity', sa.Float(), nullable=True),
                    sa.Column('Amount', sa.Float(), nullable=True),
                    sa.Column('ID_FDItem', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_FinancialDoc',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_FinancialDoc'], [
                        'financial_document.ID_FinancialDoc'], ),
                    sa.PrimaryKeyConstraint('ID_FDItem')
                    )
    op.create_table('opportunities_skills',
                    sa.Column(
                        'opport_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'skills_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['opport_id'], ['opportunities.ID_Opportunities'], ),
                    sa.ForeignKeyConstraint(
                        ['skills_id'], ['skills.ID_Skill'], ),
                    sa.PrimaryKeyConstraint('opport_id', 'skills_id')
                    )
    op.create_table('opportunities_subcontractors',
                    sa.Column(
                        'opport_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'subcon_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'State', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['opport_id'], ['opportunities.ID_Opportunities'], ),
                    sa.ForeignKeyConstraint(
                        ['subcon_id'], ['subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('opport_id', 'subcon_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities_subcontractors')
    op.drop_table('opportunities_skills')
    op.drop_table('financial_doc_item')
    op.drop_table('fdocument_ftransaction')
    op.drop_table('tlactivity')
    op.drop_index(op.f('ix_tasks_podio_item_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('permission_tech')
    op.drop_table('opportunities')
    op.drop_table('job_subcontractor')
    op.drop_table('job_payment_unit')
    op.drop_table('job_multiplier_range')
    op.drop_table('job_member')
    op.drop_table('financial_document')
    op.drop_table('estimate_cost')
    op.drop_table('change_order')
    op.drop_table('attachments')
    op.drop_table('technician')
    op.drop_table('skills_subcontractors')
    op.drop_table('permission_member')
    op.drop_table('order')
    op.drop_index(op.f('ix_jobs_podio_item_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('client_member')
    op.drop_table('client_manager')
    op.drop_table('subcontractor')
    op.drop_table('permission_role')
    op.drop_table('member')
    op.drop_table('manager')
    op.drop_index(op.f('ix_client_podio_item_id'), table_name='client')
    op.drop_table('client')
    op.drop_table('supplier')
    op.drop_table('skills')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('payment_unit')
    op.drop_table('parent_mgmt_co')
    op.drop_table('multiplier_range')
    op.drop_table('financial_transaction')
    # ### end Alembic commands ###
