"""modify tlactivity relationships.

Revision ID: 2f76ef8e83b6
Revises: ebeec6ce22de
Create Date: 2026-03-30 14:18:44.065202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f76ef8e83b6'
down_revision: Union[str, Sequence[str], None] = 'ebeec6ce22de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tlactivity', sa.Column(
        'ID_Client', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tlactivity', sa.Column('ID_Community_Tracking',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'tlactivity', 'parent_mgmt_co', [
                          'ID_Community_Tracking'], ['ID_Community_Tracking'])
    op.create_foreign_key(None, 'tlactivity', 'client',
                          ['ID_Client'], ['ID_Client'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tlactivity', type_='foreignkey')
    op.drop_constraint(None, 'tlactivity', type_='foreignkey')
    op.drop_column('tlactivity', 'ID_Community_Tracking')
    op.drop_column('tlactivity', 'ID_Client')
    # ### end Alembic commands ###
