"""MODIFY Modelo Jobs and Order para sincronizacion con Podio 2.

Revision ID: 49e9c40e3bca
Revises: 6a2eb5788710
Create Date: 2026-02-04 20:47:56.630549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e9c40e3bca'
down_revision: Union[str, Sequence[str], None] = '6a2eb5788710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Acc_receivable', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Gqm_final_form_pricing', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Gqm_final_adj_form_pricing', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Gqm_final_target_return', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Gqm_final_prem_in_money', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('Ptl_hd_materials', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'Ptl_hd_materials')
    op.drop_column('jobs', 'Gqm_final_prem_in_money')
    op.drop_column('jobs', 'Gqm_final_target_return')
    op.drop_column('jobs', 'Gqm_final_adj_form_pricing')
    op.drop_column('jobs', 'Gqm_final_form_pricing')
    op.drop_column('jobs', 'Acc_receivable')
    # ### end Alembic commands ###
