"""ADD Cambios a modelos para sincronizar con Podio.

Revision ID: 54e923519e95
Revises: 11e2c22efef4
Create Date: 2026-01-28 21:39:39.916851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '54e923519e95'
down_revision: Union[str, Sequence[str], None] = '11e2c22efef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_manager', sa.Column(
        'rol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subcontractor', sa.Column('podio_item_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subcontractor_podio_item_id'),
                    'subcontractor', ['podio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcontractor_podio_item_id'),
                  table_name='subcontractor')
    op.drop_column('subcontractor', 'podio_item_id')
    op.drop_column('client_manager', 'rol')
    # ### end Alembic commands ###
