"""MODIFY Modelo Jobs and Order para sincronizacion con Podio.

Revision ID: 6a2eb5788710
Revises: 969d542d0add
Create Date: 2026-02-03 14:45:43.610907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a2eb5788710'
down_revision: Union[str, Sequence[str], None] = '969d542d0add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Ptl_Superintendent',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('Ptl_property_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Ptl_gc_fee', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column(
        'Notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'Notes')
    op.drop_column('jobs', 'Ptl_gc_fee')
    op.drop_column('jobs', 'Ptl_property_id')
    op.drop_column('jobs', 'Ptl_Superintendent')
    # ### end Alembic commands ###
