"""modify permission model

Revision ID: 6bf35f1f3c67
Revises: 2f76ef8e83b6
Create Date: 2026-03-31 17:02:34.392535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bf35f1f3c67'
down_revision: Union[str, Sequence[str], None] = '2f76ef8e83b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('Document', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('permission', 'Action')
    op.drop_column('permission', 'Service_Associated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('Service_Associated', postgresql.ENUM('Job', 'Subcontractor', 'GQM_Member', 'Technician', 'Client', 'Dashboard', name='servicetype'), autoincrement=False, nullable=False))
    op.add_column('permission', sa.Column('Action', postgresql.ENUM('View', 'Create', 'Edit', 'Delete', name='actiontype'), autoincrement=False, nullable=False))
    op.drop_column('permission', 'Document')
    # ### end Alembic commands ###
