"""ADD podio item id a modelo Parent Mgmt Co

Revision ID: 76fa4ac1b809
Revises: 2ae2b1740857
Create Date: 2026-01-21 14:18:38.859164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76fa4ac1b809'
down_revision: Union[str, Sequence[str], None] = '2ae2b1740857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_mgmt_co', sa.Column('podio_item_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_parent_mgmt_co_podio_item_id'),
                    'parent_mgmt_co', ['podio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_mgmt_co_podio_item_id'),
                  table_name='parent_mgmt_co')
    op.drop_column('parent_mgmt_co', 'podio_item_id')
    # ### end Alembic commands ###
