"""change ptl_gc_fees to float

Revision ID: 783621614871
Revises: 0f30cb1e8da7
Create Date: 2026-03-18 14:50:12.589460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783621614871'
down_revision: Union[str, Sequence[str], None] = '0f30cb1e8da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'Ptl_gc_fee',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Float(),
                    existing_nullable=True,
                    postgresql_using='"Ptl_gc_fee"::float')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'Ptl_gc_fee',
                    existing_type=sa.Float(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True,
                    postgresql_using='"Ptl_gc_fee"::text')
    # ### end Alembic commands ###
