"""MODIFY Modelo Member para relación por app.

Revision ID: 7a201fb92740
Revises: f4fed8e5fd57
Create Date: 2026-02-11 20:25:35.528080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a201fb92740'
down_revision: Union[str, Sequence[str], None] = 'f4fed8e5fd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('podio_item_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_member_podio_item_id'),
                    'member', ['podio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_podio_item_id'), table_name='member')
    op.drop_column('member', 'podio_item_id')
    # ### end Alembic commands ###
