"""MODIFY Campo Vendor_Customer por eescribir mal Customer.

Revision ID: 7cdf94b0f95a
Revises: cc256ba73240
Create Date: 2026-02-23 13:08:55.446266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cdf94b0f95a'
down_revision: Union[str, Sequence[str], None] = 'cc256ba73240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_document', sa.Column(
        'Vendor_Customer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('financial_document', 'Vendor_Costumer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_document', sa.Column(
        'Vendor_Costumer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('financial_document', 'Vendor_Customer')
    # ### end Alembic commands ###
