"""Add order and opportunity relationship

Revision ID: 881887fe30d3
Revises: 9e22c4f94174
Create Date: 2026-05-08 22:53:38.555527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '881887fe30d3'
down_revision: Union[str, Sequence[str], None] = '9e22c4f94174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('ID_Order', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'order', ['ID_Order'], ['ID_Order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'ID_Order')
    # ### end Alembic commands ###
