"""ADD Modelo Order y relación con Job.

Revision ID: 8ac1cc4e518d
Revises: 49e9c40e3bca
Create Date: 2026-02-09 11:40:27.014629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ac1cc4e518d'
down_revision: Union[str, Sequence[str], None] = '49e9c40e3bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bldg_dept',
                    sa.Column(
                        'City_BldgDept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Office_Email', sa.JSON(), nullable=True),
                    sa.Column('Portal_Log_In',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'PW', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Phone', sa.JSON(), nullable=True),
                    sa.Column(
                        'Link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Notes_Inspectors',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_BldgDept', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('podio_item_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('ID_BldgDept')
                    )
    op.create_index(op.f('ix_bldg_dept_podio_item_id'),
                    'bldg_dept', ['podio_item_id'], unique=False)
    op.add_column('jobs', sa.Column(
        'ID_BldgDept', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'bldg_dept', [
                          'ID_BldgDept'], ['ID_BldgDept'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'ID_BldgDept')
    op.drop_index(op.f('ix_bldg_dept_podio_item_id'), table_name='bldg_dept')
    op.drop_table('bldg_dept')
    # ### end Alembic commands ###
