"""ADD Actualización del modelo Member.

Revision ID: 8fecb27a19e8
Revises: 05e09eb4c6f0
Create Date: 2026-01-30 15:25:25.698074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fecb27a19e8'
down_revision: Union[str, Sequence[str], None] = '05e09eb4c6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('Company_Role',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('member', sa.Column('podio_user_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_member_podio_user_id'),
                    'member', ['podio_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_podio_user_id'), table_name='member')
    op.drop_column('member', 'podio_user_id')
    op.drop_column('member', 'Company_Role')
    # ### end Alembic commands ###
