"""Add password and permissions to subcontractor

Revision ID: 91bd14fe27cc
Revises: abcdef123456
Create Date: 2026-06-11 16:58:41.332797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '91bd14fe27cc'
down_revision: Union[str, Sequence[str], None] = 'abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_subc',
    sa.Column('permission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.ID_Permission'], ),
    sa.ForeignKeyConstraint(['subc_id'], ['subcontractor.ID_Subcontractor'], ),
    sa.PrimaryKeyConstraint('permission_id', 'subc_id')
    )
    op.add_column('subcontractor', sa.Column('Password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcontractor', 'Password')
    op.drop_table('permission_subc')
    # ### end Alembic commands ###
