"""MODIFY Modelos para migración con Podio.

Revision ID: 969d542d0add
Revises: 09d414398455
Create Date: 2026-02-03 09:37:12.084817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '969d542d0add'
down_revision: Union[str, Sequence[str], None] = '09d414398455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_member', sa.Column(
        'rol', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('Additional_detail',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Estimated_rent', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Estimated_material', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Estimated_city', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Tech_formula_pricing', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Pricing_target',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Permit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Gqm_total_materials_fees', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column(
        'Gqm_paid_fees', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('Bldg_dept_fees',
                  postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'Bldg_dept_fees')
    op.drop_column('jobs', 'Gqm_paid_fees')
    op.drop_column('jobs', 'Gqm_total_materials_fees')
    op.drop_column('jobs', 'Permit')
    op.drop_column('jobs', 'Pricing_target')
    op.drop_column('jobs', 'Tech_formula_pricing')
    op.drop_column('jobs', 'Estimated_city')
    op.drop_column('jobs', 'Estimated_material')
    op.drop_column('jobs', 'Estimated_rent')
    op.drop_column('jobs', 'Additional_detail')
    op.drop_column('job_member', 'rol')
    # ### end Alembic commands ###
