"""Add Residential_units to client model

Revision ID: 9cf8011e0a41
Revises: 28b4126e75fc
Create Date: 2026-05-08 21:33:44.988270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf8011e0a41'
down_revision: Union[str, Sequence[str], None] = '28b4126e75fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('Residential_Units', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'Residential_Units')
    # ### end Alembic commands ###
