"""[ADD] attachments_podio_id

Revision ID: 9d1d91bc81c5
Revises: b72ce4b8d024
Create Date: 2026-03-16 15:03:50.188389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d1d91bc81c5'
down_revision: Union[str, Sequence[str], None] = 'b72ce4b8d024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('podio_file_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_attachments_podio_file_id'),
                    'attachments', ['podio_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_podio_file_id'),
                  table_name='attachments')
    op.drop_column('attachments', 'podio_file_id')
    # ### end Alembic commands ###
