"""Add president fields to ParentMgmtCo

Revision ID: 9e22c4f94174
Revises: 9cf8011e0a41
Create Date: 2026-05-08 21:47:42.167082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e22c4f94174'
down_revision: Union[str, Sequence[str], None] = '9cf8011e0a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_mgmt_co', sa.Column('President_Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('parent_mgmt_co', sa.Column('President_Email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('parent_mgmt_co', sa.Column('President_Phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_mgmt_co', 'President_Phone')
    op.drop_column('parent_mgmt_co', 'President_Email')
    op.drop_column('parent_mgmt_co', 'President_Name')
    # ### end Alembic commands ###
