"""add_job_technician

Revision ID: a16928946379
Revises: 91bd14fe27cc
Create Date: 2026-06-11 18:49:51.838706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a16928946379'
down_revision: Union[str, Sequence[str], None] = '91bd14fe27cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_technician',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technician_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.ID_Jobs'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.ID_Technician'], ),
    sa.PrimaryKeyConstraint('job_id', 'technician_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_technician')
    # ### end Alembic commands ###
