"""add reimbursement and inventory models

Revision ID: a7918ebaa3aa
Revises: b2b05d0d1b23
Create Date: 2026-03-26 22:57:05.119605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7918ebaa3aa'
down_revision: Union[str, Sequence[str], None] = 'b2b05d0d1b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
                    sa.Column(
                        'Equip_Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Cost', sa.Float(), nullable=True),
                    sa.Column('Serial_Number',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Date_Purchase', sa.DateTime(), nullable=True),
                    sa.Column(
                        'Tag_ID', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Internal_Notes',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Inventory', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('ID_Inventory')
                    )
    op.create_table('reimbursement',
                    sa.Column(
                        'Reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Value', sa.Float(), nullable=True),
                    sa.Column('ID_Reimbursement',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ID_Commission',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Commission'], ['commission.ID_Commission'], ),
                    sa.PrimaryKeyConstraint('ID_Reimbursement')
                    )
    op.add_column('attachments', sa.Column('ID_Inventory',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'inventory', [
                          'ID_Inventory'], ['ID_Inventory'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'ID_Inventory')
    op.drop_table('reimbursement')
    op.drop_table('inventory')
    # ### end Alembic commands ###
