"""Add podio failed syncs table

Revision ID: abcdef123456
Revises: 881887fe30d3
Create Date: 2026-05-25 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'abcdef123456'
down_revision: Union[str, Sequence[str], None] = '881887fe30d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podio_failed_syncs',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hook_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podio_failed_syncs_item_id'), 'podio_failed_syncs', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podio_failed_syncs_item_id'), table_name='podio_failed_syncs')
    op.drop_table('podio_failed_syncs')
    # ### end Alembic commands ###
