"""MODIFY Modelos financieros para ajuste y mejor compatibilidad con QBO y ajustes en los modelos Order y ChangeOrder.

Revision ID: af80f381ab9c
Revises: 7cdf94b0f95a
Create Date: 2026-03-02 20:16:58.888042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af80f381ab9c'
down_revision: Union[str, Sequence[str], None] = '7cdf94b0f95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_financial_document_qbo_id'), 'financial_document', ['qbo_id'], unique=True)
    op.create_index(op.f('ix_financial_transaction_qbo_id'), 'financial_transaction', ['qbo_id'], unique=True)
    op.drop_column('order', 'notes_field')
    op.drop_column('order', 'hd_materials_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('hd_materials_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('notes_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_financial_transaction_qbo_id'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_document_qbo_id'), table_name='financial_document')
    # ### end Alembic commands ###
