"""add commission models

Revision ID: b2b05d0d1b23
Revises: bd4b154274bc
Create Date: 2026-03-25 15:47:33.620073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2b05d0d1b23'
down_revision: Union[str, Sequence[str], None] = 'bd4b154274bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
                    sa.Column(
                        'Month', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Year', sa.Integer(), nullable=True),
                    sa.Column('Total_commission', sa.Float(), nullable=True),
                    sa.Column('Total_margin', sa.Float(), nullable=True),
                    sa.Column('Total_reimbursment', sa.Float(), nullable=True),
                    sa.Column('ID_Commission',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'ID_Member', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Member'], ['member.ID_Member'], ),
                    sa.PrimaryKeyConstraint('ID_Commission')
                    )
    op.create_table('commission_group',
                    sa.Column(
                        'Jobs_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Jobs_year', sa.Integer(), nullable=True),
                    sa.Column(
                        'Rol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Total_detail', sa.Float(), nullable=True),
                    sa.Column('ID_ComGroup', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_Commission',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_Commission'], ['commission.ID_Commission'], ),
                    sa.PrimaryKeyConstraint('ID_ComGroup')
                    )
    op.create_table('commission_detail',
                    sa.Column('Factor', sa.Float(), nullable=True),
                    sa.Column('Sell_Mgmt', sa.Float(), nullable=True),
                    sa.Column('ID_ComDetail', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('ID_ComGroup', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column(
                        'ID_Jobs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['ID_ComGroup'], ['commission_group.ID_ComGroup'], ),
                    sa.ForeignKeyConstraint(['ID_Jobs'], ['jobs.ID_Jobs'], ),
                    sa.PrimaryKeyConstraint('ID_ComDetail')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_detail')
    op.drop_table('commission_group')
    op.drop_table('commission')
    # ### end Alembic commands ###
