"""add date end fields to jobs

Revision ID: b72ce4b8d024
Revises: b1fdb44e385f
Create Date: 2026-03-06 11:42:14.630855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72ce4b8d024'
down_revision: Union[str, Sequence[str], None] = 'b1fdb44e385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Date_assigned_end', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('Estimated_start_date_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'Estimated_start_date_end')
    op.drop_column('jobs', 'Date_assigned_end')
    # ### end Alembic commands ###
