"""add amount_applied and date_applied to financial_link

Revision ID: bd4b154274bc
Revises: 783621614871
Create Date: 2026-03-20 16:05:59.131908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4b154274bc'
down_revision: Union[str, Sequence[str], None] = '783621614871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fdocument_ftransaction', sa.Column('amount_applied', sa.Float(), nullable=True))
    op.add_column('fdocument_ftransaction', sa.Column('date_applied', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fdocument_ftransaction', 'date_applied')
    op.drop_column('fdocument_ftransaction', 'amount_applied')
    # ### end Alembic commands ###
