"""Cambios a modelos tasks, attachments y chat.

Revision ID: cbdd681a9cbb
Revises: ee4da8bd8afa
Create Date: 2026-04-23 21:45:12.551582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbdd681a9cbb'
down_revision: Union[str, Sequence[str], None] = 'ee4da8bd8afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column(
        'ID_BldgDept', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('attachments', sa.Column('ID_ChatMessage',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'chat_message', [
                          'ID_ChatMessage'], ['ID_ChatMessage'])
    op.create_foreign_key(None, 'attachments', 'bldg_dept', [
                          'ID_BldgDept'], ['ID_BldgDept'])
    op.drop_constraint(op.f('tasks_ID_Jobs_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'jobs', ['ID_Jobs'], [
                          'ID_Jobs'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ID_Jobs_fkey'),
                          'tasks', 'jobs', ['ID_Jobs'], ['ID_Jobs'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'ID_ChatMessage')
    op.drop_column('attachments', 'ID_BldgDept')
    # ### end Alembic commands ###
