"""MODIFY Modelos Financial Doc and Trans para conexión con QBO.

Revision ID: cc256ba73240
Revises: d2195f5684b7
Create Date: 2026-02-23 12:43:05.874333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cc256ba73240'
down_revision: Union[str, Sequence[str], None] = 'd2195f5684b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_document', sa.Column(
        'is_emailed', sa.Boolean(), nullable=True))
    op.add_column('financial_document', sa.Column(
        'is_voided', sa.Boolean(), nullable=True))
    op.add_column('financial_document', sa.Column(
        'Vendor_Costumer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('financial_document_ID_Order_fkey'),
                       'financial_document', type_='foreignkey')
    op.drop_constraint(op.f('financial_document_ID_Client_fkey'),
                       'financial_document', type_='foreignkey')
    op.drop_constraint(op.f('financial_document_ID_Subcontractor_fkey'),
                       'financial_document', type_='foreignkey')
    op.drop_column('financial_document', 'ID_Order')
    op.drop_column('financial_document', 'ID_Client')
    op.drop_column('financial_document', 'ID_Subcontractor')
    op.add_column('financial_transaction', sa.Column(
        'is_emailed', sa.Boolean(), nullable=True))
    op.add_column('financial_transaction', sa.Column(
        'is_voided', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_transaction', 'is_voided')
    op.drop_column('financial_transaction', 'is_emailed')
    op.add_column('financial_document', sa.Column(
        'ID_Subcontractor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('financial_document', sa.Column(
        'ID_Client', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('financial_document', sa.Column(
        'ID_Order', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('financial_document_ID_Subcontractor_fkey'),
                          'financial_document', 'subcontractor', ['ID_Subcontractor'], ['ID_Subcontractor'])
    op.create_foreign_key(op.f('financial_document_ID_Client_fkey'),
                          'financial_document', 'client', ['ID_Client'], ['ID_Client'])
    op.create_foreign_key(op.f('financial_document_ID_Order_fkey'),
                          'financial_document', 'order', ['ID_Order'], ['ID_Order'])
    op.drop_column('financial_document', 'Vendor_Costumer')
    op.drop_column('financial_document', 'is_voided')
    op.drop_column('financial_document', 'is_emailed')
    # ### end Alembic commands ###
