"""ADD Actualización del campo de referencia a podio en el modelo Member.

Revision ID: d0eee064fa99
Revises: 8fecb27a19e8
Create Date: 2026-01-30 17:13:42.716618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0eee064fa99'
down_revision: Union[str, Sequence[str], None] = '8fecb27a19e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('podio_profile_id',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_member_podio_user_id'), table_name='member')
    op.create_index(op.f('ix_member_podio_profile_id'),
                    'member', ['podio_profile_id'], unique=False)
    op.drop_column('member', 'podio_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('podio_user_id',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_member_podio_profile_id'), table_name='member')
    op.create_index(op.f('ix_member_podio_user_id'),
                    'member', ['podio_user_id'], unique=False)
    op.drop_column('member', 'podio_profile_id')
    # ### end Alembic commands ###
