"""MODIFY Modelo FDocItem para agregar referencia interna de QBO.

Revision ID: d2195f5684b7
Revises: f2f62836abe4
Create Date: 2026-02-19 11:31:18.559275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2195f5684b7'
down_revision: Union[str, Sequence[str], None] = 'f2f62836abe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_doc_item', sa.Column(
        'qbo_line_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_doc_item', 'qbo_line_id')
    # ### end Alembic commands ###
