"""MODIFY Modelos Change Order y Order para relación con Podio.

Revision ID: de45bf75da50
Revises: 0e518cb3f9db
Create Date: 2026-02-14 01:17:19.355064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de45bf75da50'
down_revision: Union[str, Sequence[str], None] = '0e518cb3f9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_order', sa.Column('chor_formula_field',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('hd_materials_field',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column(
        'notes_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'notes_field')
    op.drop_column('order', 'hd_materials_field')
    op.drop_column('change_order', 'chor_formula_field')
    # ### end Alembic commands ###
