"""DELETE Parent Mgmt Co del modelo Client

Revision ID: eb2f970986a0
Revises: 76fa4ac1b809
Create Date: 2026-01-21 17:35:00.356192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2f970986a0'
down_revision: Union[str, Sequence[str], None] = '76fa4ac1b809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'Parent_Mgmt_Company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('Parent_Mgmt_Company', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
