"""[ADD] Nuevo modelo Certificate y cambios a purchases models. 

Revision ID: ee4da8bd8afa
Revises: 1c3b6eca42b5
Create Date: 2026-04-16 11:47:03.273019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee4da8bd8afa'
down_revision: Union[str, Sequence[str], None] = '1c3b6eca42b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
                    sa.Column(
                        'Name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'Status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Expiration_date', sa.Date(), nullable=True),
                    sa.Column(
                        'Notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('Current_doc_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('ID_Certificate',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ID_Subcontractor',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['ID_Subcontractor'], [
                        'subcontractor.ID_Subcontractor'], ),
                    sa.PrimaryKeyConstraint('ID_Certificate')
                    )
    op.add_column('attachments', sa.Column('ID_Certificate',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'certificate', [
                          'ID_Certificate'], ['ID_Certificate'])
    op.drop_column('purchase', 'Purchase_note')
    op.add_column('purchase_order_item', sa.Column(
        'Quote_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchase_order_item', sa.Column(
        'Purchase_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_item', 'Purchase_notes')
    op.drop_column('purchase_order_item', 'Quote_notes')
    op.add_column('purchase', sa.Column('Purchase_note',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'ID_Certificate')
    op.drop_table('certificate')
    # ### end Alembic commands ###
