"""MODIFY Modelo Change Order para eliminar campo sobrante.

Revision ID: f2f62836abe4
Revises: de45bf75da50
Create Date: 2026-02-14 20:24:10.759334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f62836abe4'
down_revision: Union[str, Sequence[str], None] = 'de45bf75da50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_order', 'chor_formula_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_order', sa.Column('chor_formula_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
