"""MODIFY Modelos para tener todas las relaciones nuevas.

Revision ID: f4fed8e5fd57
Revises: 8ac1cc4e518d
Create Date: 2026-02-10 15:23:13.784479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4fed8e5fd57'
down_revision: Union[str, Sequence[str], None] = '8ac1cc4e518d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column(
        'ID_Supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('attachments', sa.Column('ID_FinancialDoc',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'supplier', [
                          'ID_Supplier'], ['ID_Supplier'])
    op.create_foreign_key(None, 'attachments', 'financial_document', [
                          'ID_FinancialDoc'], ['ID_FinancialDoc'])
    op.add_column('change_order', sa.Column(
        'ID_Order', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'change_order', 'order',
                          ['ID_Order'], ['ID_Order'])
    op.drop_column('manager', 'Rol')
    op.add_column('tasks', sa.Column(
        'ID_Member', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'member', [
                          'ID_Member'], ['ID_Member'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'ID_Member')
    op.add_column('manager', sa.Column('Rol', sa.VARCHAR(),
                  autoincrement=False, nullable=True))
    op.drop_constraint(None, 'change_order', type_='foreignkey')
    op.drop_column('change_order', 'ID_Order')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'ID_FinancialDoc')
    op.drop_column('attachments', 'ID_Supplier')
    # ### end Alembic commands ###
